# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='log_reg.User')),
                ('second_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='log_reg.User')),
            ],
        ),
    ]
